export const seedData = {
  users: [
    {
      id: 'user-admin',
      name: 'Administrador Osake',
      role: 'admin',
      phone: '+56911111111',
      email: 'admin@osake.local',
      extraFields: {},
    },
    {
      id: 'user-compras',
      name: 'Equipo Compras',
      role: 'buyer',
      phone: '+56922222222',
      email: 'compras@osake.local',
      extraFields: {},
    },
  ],
  suppliers: [
    {
      id: 'supplier-cocacola',
      name: 'Coca-Cola',
      sellerName: 'Jorge',
      sellerPhone: '+56987654321',
      category: 'Bebidas',
      deliveryLeadTime: '24 horas',
      deliveryDays: 'Lunes a sabado',
      paymentTerms: 'Credito semanal',
      notes: 'Vendedor principal para bebidas y promociones.',
      extraFields: {},
      products: [
        {
          id: 'product-coke-zero-15',
          name: 'Coca-Cola',
          variety: 'Zero',
          size: '1.5L',
          format: 'Botella PET',
          unitPrice: 1890,
          deliveryOverride: '',
          minimumOrder: 4,
          note: 'Revisar stock de frio.',
          extraFields: {},
        },
        {
          id: 'product-fanta-3',
          name: 'Fanta',
          variety: 'Naranja',
          size: '3L',
          format: 'Botella PET',
          unitPrice: 2590,
          deliveryOverride: '',
          minimumOrder: 3,
          note: '',
          extraFields: {},
        },
        {
          id: 'product-sprite-1',
          name: 'Sprite',
          variety: 'Sin azucar',
          size: '1L',
          format: 'Botella PET',
          unitPrice: 1490,
          deliveryOverride: '',
          minimumOrder: 6,
          note: '',
          extraFields: {},
        },
      ],
    },
    {
      id: 'supplier-salmones',
      name: 'Salmones del Sur',
      sellerName: 'Gonzalo',
      sellerPhone: '+56999887766',
      category: 'Pescados',
      deliveryLeadTime: '48 horas',
      deliveryDays: 'Martes y viernes',
      paymentTerms: 'Transferencia',
      notes: 'Confirmar corte y frescura antes de despacho.',
      extraFields: {},
      products: [
        {
          id: 'product-salmon-trim',
          name: 'Salmon fresco',
          variety: 'Trim E',
          size: '17 kg',
          format: 'Caja',
          unitPrice: 12300,
          deliveryOverride: '48 horas',
          minimumOrder: 1,
          note: 'Similar a la planilla Restomarket.',
          extraFields: {},
        },
        {
          id: 'product-salmon-porcion',
          name: 'Salmon porcionado',
          variety: 'Premium',
          size: '5 kg',
          format: 'Bolsa al vacio',
          unitPrice: 31800,
          deliveryOverride: '72 horas',
          minimumOrder: 1,
          note: '',
          extraFields: {},
        },
      ],
    },
    {
      id: 'supplier-hielo',
      name: 'Quiero Hielo',
      sellerName: 'Duilio',
      sellerPhone: '+56964945128',
      category: 'Congelados',
      deliveryLeadTime: 'Despacho entre martes y miercoles',
      deliveryDays: 'Pedido martes',
      paymentTerms: 'Efectivo caja',
      notes: 'Inspirado en la planilla SM.',
      extraFields: {},
      products: [
        {
          id: 'product-hielo-cristal',
          name: 'Hielo',
          variety: 'Cristal',
          size: '10 kg',
          format: 'Malla',
          unitPrice: 450,
          deliveryOverride: '',
          minimumOrder: 3,
          note: '',
          extraFields: {},
        },
      ],
    },
  ],
  customFields: {
    supplier: [],
    product: [],
    order: [],
    user: [],
  },
}
